# Generated by Django 5.0.7 on 2024-08-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='location_in_store',
        ),
    ]
