# Generated by Django 5.0.7 on 2024-08-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_location_product_location_in_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location_in_store',
            new_name='location',
        ),
    ]
